In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tqdm import tqdm

In [2]:
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 18044312295152168282
xla_global_id: -1
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 6475376230
locality {
  bus_id: 1
  links {
  }
}
incarnation: 3924771105735373762
physical_device_desc: "device: 0, name: NVIDIA GeForce GTX 1080, pci bus id: 0000:03:00.0, compute capability: 6.1"
xla_global_id: 416903419
]


In [3]:
bar = tqdm(total=4)
bar.set_description("Raspakek data")

inputLines = np.load('traindata/inputLines.npy')/256
bar.update(1)

service = np.load('traindata/service.npy')
bar.update(1)

binaryData = np.load('traindata/binaryData.npy')
bar.update(1)

#blockL0 = np.load('traindata/blockL0.npy')
#bar.update(1)
#
#blockR0 = np.load('traindata/blockR0.npy')
#bar.update(1)
#
#blockL1 = np.load('traindata/blockL1.npy')
#bar.update(1)
#
#blockR1 = np.load('traindata/blockR1.npy')
#bar.update(1)
#
#blockL2 = np.load('traindata/blockL2.npy')
#bar.update(1)
#
#blockR2 = np.load('traindata/blockR2.npy')
#bar.update(1)

#remove all data after 100000 pos
if False:
    remAftr = 100000
    inputLines = inputLines[:remAftr]
    service = service[:remAftr]
    blockL0 = blockL0[:remAftr]
    blockR0 = blockR0[:remAftr]
    blockL1 = blockL1[:remAftr]
    blockR1 = blockR1[:remAftr]
    blockL2 = blockL2[:remAftr]
    blockR2 = blockR2[:remAftr]

#target_data = {'service': service, 'blockL0': blockL0, 'blockR0':blockR0, 'blockL1':blockL1, 'blockR1':blockR1, 'blockL2':blockL2, 'blockR2':blockR2}
target_data = {'service': service, 'binaryData':binaryData}
bar.update(1)
bar.close()

Raspakek data: 100%|█████████████████████████████████████████████████████████████████████| 4/4 [00:14<00:00,  3.74s/it]


In [7]:
inputLines[5151]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.46875   , 0.58203125, 0.58203125, 0.58203125, 0.58203125,
       0.2109375 , 0.        , 0.        , 0.        , 0.        ,
       0.265625  , 0.58203125, 0.58203125, 0.58203125, 0.58203125,
       0.4140625 , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.52734375, 0.58203125, 0.58203125, 0.58203125,
       0.58203125, 0.15234375, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.22265625, 0.58203125, 0.58203125, 0.58203125,
       0.58203125, 0.4609375 , 0.        , 0.        , 0.        ,
       0.        , 0.01953125, 0.58203125, 0.58203125, 0.58203125,
       0.58203125, 0.58203125, 0.09765625, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [8]:
binaryData[5151]

array([ True, False,  True, False, False,  True, False, False,  True,
       False,  True, False, False, False, False,  True,  True, False,
        True, False,  True, False, False,  True, False, False,  True,
       False,  True, False,  True, False, False, False,  True, False,
        True, False,  True,  True,  True,  True,  True, False,  True,
       False, False, False,  True, False,  True,  True, False,  True,
       False, False, False, False,  True, False,  True,  True, False,
        True, False, False,  True, False, False,  True, False,  True,
       False, False,  True, False, False, False, False, False, False,
        True,  True, False,  True, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True, False,
       False,  True, False, False, False, False,  True, False, False,
       False,  True, False,  True, False,  True,  True, False, False,
       False,  True,

In [9]:
service[5151]

array([ True, False])

In [9]:
model = keras.models.load_model("model")

In [32]:
input = keras.Input(720, )
x = layers.Dense(137, activation='linear', use_bias=True, bias_initializer='zeros')(input)
#x = layers.Dropout(0.1)(x)
x = layers.Dense(137, activation='linear', use_bias=True, bias_initializer='zeros')(x)

service = layers.Dense(2 , activation='sigmoid', name='service')(service)
tf.math.sigmoid(x)
tf.math.sigmoid(x)
binaryData = layers.Dense(137 , activation='sigmoid', name='binaryData')(binaryData)
#blockL0 = layers.Dense(16, activation='sigmoid', use_bias=True, bias_initializer='zeros', name='blockL0')(x)
#blockR0 = layers.Dense(16, activation='sigmoid', use_bias=True, bias_initializer='zeros', name='blockR0')(x)
#blockL1 = layers.Dense(16, activation='sigmoid', use_bias=True, bias_initializer='zeros', name='blockL1')(x)
#blockR1 = layers.Dense(16, activation='sigmoid', use_bias=True, bias_initializer='zeros', name='blockR1')(x)
#blockL2 = layers.Dense(16, activation='sigmoid', use_bias=True, bias_initializer='zeros', name='blockL2')(x)
#blockR2 = layers.Dense(16, activation='sigmoid', use_bias=True, bias_initializer='zeros', name='blockR2')(x)


#model = keras.Model(input, [service, blockL0, blockR0, blockL1, blockR1, blockL2, blockR2])
model = keras.Model(input, [service, binaryData])


model.summary()

tf.keras.utils.plot_model(
    model,
    to_file="model.png",
    show_shapes=True,
    show_dtype=False,
    show_layer_names=True,
    rankdir="TB",
    expand_nested=True,
    dpi=96,
    layer_range=None,
    show_layer_activations=True,
)

#visualizer(model, format='png', view=True)


ValueError: Graph disconnected: cannot obtain value for tensor KerasTensor(type_spec=TensorSpec(shape=(None, 720), dtype=tf.float32, name='input_2'), name='input_2', description="created by layer 'input_2'") at layer "dense_4". The following previous layers were accessed without issue: []

In [19]:

model.compile(loss='mean_squared_error',
              optimizer='adam',
              metrics=['binary_accuracy'])


In [20]:
model.fit(inputLines, target_data, epochs=1)

Epoch 1/3
29223/29223 [==============================] - 311s 11ms/step - loss: 0.0734 - service_loss: 0.0033 - binaryData_loss: 0.0701 - service_binary_accuracy: 0.9998 - binaryData_binary_accuracy: 0.9031
Epoch 2/3
29223/29223 [==============================] - 355s 12ms/step - loss: 0.0436 - service_loss: 6.4871e-09 - binaryData_loss: 0.0436 - service_binary_accuracy: 1.0000 - binaryData_binary_accuracy: 0.9423
Epoch 3/3
 8664/29223 [=======>......................] - ETA: 4:21 - loss: 0.0381 - service_loss: 1.9777e-09 - binaryData_loss: 0.0381 - service_binary_accuracy: 1.0000 - binaryData_binary_accuracy: 0.9501

KeyboardInterrupt: 

In [7]:
model.save("model")

INFO:tensorflow:Assets written to: model\assets


In [31]:
print(model.predict(np.array([inputLines[5]])))

[array([[1.5477517e-04, 7.7058168e-05]], dtype=float32), array([[1.07869343e-03, 5.45098956e-05, 1.03853061e-03, 5.92705182e-05,
        8.54914106e-05, 3.71981441e-04, 3.40228667e-04, 7.58250884e-04,
        1.18048119e-05, 1.35251757e-04, 1.03420613e-03, 1.17235782e-03,
        1.84291101e-03, 3.20153390e-06, 9.52157716e-05, 1.07106019e-03,
        8.88990962e-06, 3.25700239e-05, 3.42334679e-04, 2.98509229e-04,
        5.07144199e-04, 3.61893704e-04, 7.14776106e-05, 7.02425081e-04,
        1.77428490e-04, 1.05157058e-04, 5.81831337e-05, 1.47321471e-03,
        2.23033999e-06, 3.44207929e-03, 1.10956622e-04, 3.48267822e-05,
        1.49982356e-04, 2.91654083e-04, 2.38680252e-04, 4.45689540e-04,
        1.56500813e-04, 2.07484671e-04, 9.62918348e-05, 9.57095122e-04,
        1.12620575e-04, 4.44069592e-05, 4.07084415e-04, 5.38571066e-06,
        1.45125559e-05, 1.11276947e-03, 1.07208900e-04, 4.60879732e-04,
        1.73590146e-04, 9.36910292e-05, 5.89446699e-06, 9.76792580e-05,
       